name: ussd_sample
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ussd_service: ^0.1.0+4
  permission_handler: ^5.0.1+1
  sim_data: ^0.0.1+2
  ussd: ^0.0.2+1



  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

